# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - run: git clone https://github.com/DataWorks-NC/quality-of-life-dashboard.git .
      - run: git checkout master
      - checkout:
          path: ~/repo/data
      - run: sed -i "s/MAPBOX_ACCESS_TOKEN/$MAPBOX_ACCESS_TOKEN/" .circleci/config.private.js
      - run: sed -i "s/ROLLBAR_ACCESS_TOKEN/$ROLLBAR_ACCESS_TOKEN/" .circleci/config.private.js
      - run: cp ./.circleci/config.private.js data/config/private.js
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          command: npm install
          environment:
            NODE_ENV: dev

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # run tests!
      - run: npm run build > npm-build-output.txt
      - run: cat npm-build-output.txt
      - run: ~/repo/data/.circleci/check-build-output-for-errors.sh
      - run: mkdir /tmp/workspace
      - persist_to_workspace:
          root: .
          paths:
            - public/*
            - .circleci/*
  # Note: Auto-pushes of data only deploy to dev; you will need to manually trigger a rebuild of the master branch
  # of the dashboard to deploy to prod.
  deploy_dev:
    docker:
      - image: microsoft/azure-cli
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: pip install -r .circleci/requirements.txt
          working_directory: /tmp/workspace/
      - run:
          command: python .circleci/deploy.py /tmp/workspace/public
          working_directory: /tmp/workspace/
          environment:
            AZURE_DESTINATION_BLOB: "dev"
  deploy_prod:
    docker:
      - image: microsoft/azure-cli
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: pip install -r .circleci/requirements.txt
          working_directory: /tmp/workspace/

      # Copy production robots.txt file.
      - run: cp /tmp/workspace/.circleci/robots-prod.txt /tmp/workspace/public/robots.txt
      - run:
          command: python .circleci/deploy.py /tmp/workspace/public
          working_directory: /tmp/workspace/
          environment:
            AZURE_DESTINATION_BLOB: "prod"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_dev:
          requires:
            - build
          filters:
            branches:
              only:
                master
      - hold:
          type: approval
          requires:
            - deploy_dev
      - deploy_prod:
          requires:
            - hold
