version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:lts-browsers

    working_directory: ~/repo
    resource_class: large

    steps:
      - run: git clone https://github.com/DataWorks-NC/quality-of-life-dashboard.git .
      - run: git checkout main
      - checkout:
          path: ~/repo/data

      - run: npm install --production=false

      - save_cache:
          paths:
            - node_modules
          key: v4-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run jest tests
          command: npm run test

      # run tests!
      - run: npm run build-data 2>&1 | tee npm-build-output-data.txt
      - store_artifacts:
          path: ~/repo/npm-build-output-data.txt
      - run: NODE_OPTIONS=--openssl-legacy-provider npm run build 2>&1 | tee npm-build-output.txt
      - store_artifacts:
          path: ~/repo/npm-build-output.txt
      - run: ~/repo/data/.circleci/check-build-output-for-errors.sh

      - run: mkdir /tmp/workspace
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  sitemap:
    docker:
      - image: cimg/node:lts-browsers

    working_directory: /tmp/workspace/

    steps:
      - attach_workspace:
          at: /tmp/workspace

      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v4-dependencies-

      # Generate a sitemap.
      - run: npm run build-sitemap

      - persist_to_workspace:
          root: .
          paths:
            - ./*

  # Note: Auto-pushes of data only deploy to dev; you will need to manually trigger a rebuild of the main branch
  # of the dashboard to deploy to prod.
  deploy_dev:
    docker:
      - image: mcr.microsoft.com/azure-cli
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: pip install -r .circleci/requirements.txt
          working_directory: /tmp/workspace/
      - run:
          command: python .circleci/deploy.py /tmp/workspace/dist
          working_directory: /tmp/workspace/
          environment:
            AZURE_DESTINATION_BLOB: "dev"
  deploy_prod:
    docker:
      - image: mcr.microsoft.com/azure-cli
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: pip install -r .circleci/requirements.txt
          working_directory: /tmp/workspace/

      # Tweak sitemap URLs
      - run: sed -i 's/nbhdcompassdev\.azurewebsites\.us/compass\.durhamnc\.gov/g' /tmp/workspace/dist/sitemap.xml

      # Copy production robots.txt file.
      - run: cp /tmp/workspace/.circleci/robots-prod.txt /tmp/workspace/dist/robots.txt
      - run:
          command: python .circleci/deploy.py /tmp/workspace/dist
          working_directory: /tmp/workspace/
          environment:
            AZURE_DESTINATION_BLOB: "prod"

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - deploy_dev:
          requires:
            - build
          filters:
            branches:
              only:
                main
      - sitemap:
          requires:
            - build
          filters:
            branches:
              only:
                main
      - hold:
          type: approval
          requires:
            - deploy_dev
      - deploy_prod:
          requires:
            - hold
            - sitemap
