// ***********************************************************
// Ye Olde Metric Configuration
//
// Here's the format:
// "m<the metric number>": {
//        "metric"        the metric number
//        "type"          Type of calculation to be performed (determines files to fetch). Options are sum, mean, and weighted.
//                            sum: r<metric>.csv
//                            mean: n<metric>.csv
//                            weighted: r<metric>.csv and d<metric>.csv
//        "category"      the category of the metric
//        "title"         metric descriptive title
//        "title_es"      Spanish-language title
//        "accuracy"      [optional] set true if metric has an accuracy file (i.e. m<metric>-accuracy.csv)
//        "label"         [optional] metric unit information
//        "decimals"      [optional] number of decimal places to display (default is 0)
//        "prefix"        [optional] prefix for the number, like '$'
//        "world_val"    [optional] override study area values for entire area via array
//                                 ex: "world_val": {"y_2013": 1234, "y_2015": 2345}
//        "suffix"        [optional] suffix for the number, like '%'
//        "raw_label"     [optional] label for raw number if available (also makes raw number visible)
//        "geographies"   [optional] list of geographies for which this metric is available. if these are used, the datagen.js script
//                        will look for files in a `geography` subdirectory of `metric` for each `geography`
// }
// ***********************************************************

module.exports = {
  'mAVEAGE': {
    'metric': 'AVEAGE',
    'category': 'Health',
    'label': 'years',
    'title': 'Average Age of Death',
    'title_es': 'Edad Promedio de Muerte',
    'decimals': 1,
    'type': 'mean',
    'world_val': {'y_2009': 69.1, 'y_2014': 69.6},
    'geographies': [
      'blockgroup',
      'tract',
    ],
  },
  'mBACH': {
    'metric': 'BACH',
    'category': 'Education',
    'suffix': '%',
    'raw_label': 'adults',
    'title_es': 'Porcentaje de adultos con licenciaturas o más',
    'title': 'Percent of Adults with a Bachelors Degree or More',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'tract',
    ],
  },
  'mBIKEWK': {
    'metric': 'BIKEWK',
    'category': 'Infrastructure and Amenities',
    'suffix': '%',
    'raw_label': 'people',
    'title': 'Commuting to Work by Bicycle',
    'title_es': 'Viaje al trabajo en bicicleta',
    'decimals': 1,
    'world_val': {
      y_2011: 0.6,
      y_2012: 0.8,
      y_2013: 0.7,
      y_2014: 0.8,
      y_2015: 0.8,
      y_2016: 0.7,
      y_2017: 0.6,
      y_2018: 0.6,
    },
    'type': 'weighted',
    'geographies': [
      'tract',
    ],
  },
  'mCC45': {
    'metric': 'CC45',
    'category': 'Education',
    'suffix': '%',
    'title': 'Child Care Centers with 4 or 5 Star Ratings',
    'title_es': 'Centros de Cuidado de Niños Calificados con 4 o 5 estrellas',
    'decimals': 1,
    'raw_label': 'centers',
    'type': 'weighted',
    'geographies': [
      'blockgroup',
    ],
  },
  'mCCC': {
    'metric': 'CCC',
    'category': 'Education',
    'title': 'Child Care Centers per Square Mile',
    'title_es': 'Centros de Cuidado de Niños por milla cuadrada',
    'label': 'centers per sq mi',
    'raw_label': 'centers',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
    ],
  },
  'mCKD_ASIAN': {
    'metric': 'CKD_ASIAN',
    'category': 'Health',
    'title': 'Chronic Kidney Disease (Asian Population)',
    'title_es': 'Enfermedad Renal Crónica (Población Asiática)',
    'subcategory': 'Chronic Kidney Disease',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 3.08, 'y_2017': 3.7},
    'geographies': [
      'tract',
    ],
  },
  'mCKD_BLACK': {
    'metric': 'CKD_BLACK',
    'category': 'Health',
    'title': 'Chronic Kidney Disease (Black or African American Population)',
    'title_es': 'Enfermedad Renal Crónica (Población Negra o Afroamericana)',
    'subcategory': 'Chronic Kidney Disease',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 9.11, 'y_2017': 9.87},
    'geographies': [
      'tract',
    ],
  },
  'mCKD_FEMALE': {
    'metric': 'CKD_FEMALE',
    'category': 'Health',
    'title': 'Chronic Kidney Disease (Female)',
    'title_es': 'Enfermedad Renal Crónica (Mujeres)',
    'subcategory': 'Chronic Kidney Disease',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 8.41, 'y_2017': 9.38},
    'geographies': [
      'tract',
    ],
  },
  'mCKD_HISPANIC': {
    'metric': 'CKD_HISPANIC',
    'category': 'Health',
    'subcategory': 'Chronic Kidney Disease',
    'title': 'Chronic Kidney Disease (Hispanic or Latino/a Population)',
    'title_es': 'Enfermedad Renal Crónica (Población Hispana o Latina)',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 2.53, 'y_2017': 3.11},
    'geographies': [
      'tract',
    ],
  },
  'mCKD_MALE': {
    'metric': 'CKD_MALE',
    'category': 'Health',
    'subcategory': 'Chronic Kidney Disease',
    'title': 'Chronic Kidney Disease (Male)',
    'title_es': 'Enfermedad Renal Crónica (Hombres)',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 8.51, 'y_2017': 9.13},
    'geographies': [
      'tract',
    ],
  },
  'mCKD_TOTAL': {
    'metric': 'CKD_TOTAL',
    'category': 'Health',
    'subcategory': 'Chronic Kidney Disease',
    'title': 'Chronic Kidney Disease (Adult Population)',
    'title_es': 'Enfermedad Renal Crónica (Población Adulta)',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 8.43, 'y_2017': 9.26},
    'geographies': [
      'tract',
    ],
  },
  'mCKD_WHITE': {
    'metric': 'CKD_WHITE',
    'category': 'Health',
    'subcategory': 'Chronic Kidney Disease',
    'title': 'Chronic Kidney Disease (White Population)',
    'title_es': 'Enfermedad Renal Crónica (Población Blanca)',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 3.27, 'y_2017': 10.75},
    'geographies': [
      'tract',
    ],
  },
  'mCLINIC': {
    'metric': 'CLINIC',
    'category': 'Health',
    'suffix': '%',
    'title': 'Homes Near Health Care Clinics',
    'title_es': 'Viviendas cerca de clínicas de salud',
    'label': 'of households',
    'raw_label': 'homes near clinics',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
    ],
  },
  'mEDUCATION-HEALTH-CARE-SOCIAL-SERVICE-WORKERS': {
    'metric': 'EDUCATION-HEALTH-CARE-SOCIAL-SERVICE-WORKERS',
    'category': 'Economy',
    'subcategory': 'Jobs',
    'accuracy': 'true',
    'suffix': '%',
    'raw_label': 'workers',
    'title': 'Percent of Workers in Educational, Health Care and Social Assistance Services',
    'title_es': 'Porcentaje de Trabajadores en Servicios de Salud, Educativos y de Asistencia Social',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'tract',
    ],
  },
  'mRETAIL-WORKERS': {
    'metric': 'RETAIL-WORKERS',
    'category': 'Economy',
    'subcategory': 'Jobs',
    'accuracy': 'true',
    'suffix': '%',
    'raw_label': 'workers',
    'title': 'Percent of Workers in the Retail Trade Industry',
    'title_es': 'Porcentaje de Trabajadores en la Industria del Comercio Minorista',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'tract',
    ],
  },
  'mACCOMMODATION-WORKERS': {
    'metric': 'ACCOMMODATION-WORKERS',
    'category': 'Economy',
    'subcategory': 'Jobs',
    'accuracy': 'true',
    'suffix': '%',
    'raw_label': 'workers',
    'title': 'Percent of Workers in the Arts, Entertainment, Recreation, and Accommodation & Food Services',
    'title_es': 'Porcentaje de Trabajadores de Actividades Artísticas, Entretenimiento, Recreación y Servicios de Alimentación y Alojamiento',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'tract',
    ],
  },
  'mCOB': {
    'metric': 'COB',
    'category': 'Economy',
    'subcategory': 'Building Permits',
    'label': 'certificates per sq mi',
    'raw_label': 'certificates',
    'title': 'Commercial Certificates of Occupancy per Sq Mile',
    'title_es': 'Certificados de Ocupación Comercial por milla cuadrada',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
    'world_val': {
      y_2012: 1.7626559013996171,
      y_2013: 1.8264472578312223,
      y_2014: 1.6921496653436325,
      y_2015: 2.2125528362330432,
      y_2016: 1.8130174985824633,
      y_2017: 1.5209202349219554,
      y_2018: 1.9003109336993968,
      y_2019: 1.6787199060948735,
    }
  },
  'mCOR': {
    'metric': 'COR',
    'category': 'Economy',
    'subcategory': 'Building Permits',
    'label': 'certificates per sq mi',
    'raw_label': 'certificates',
    'title': 'Residential Certificates of Occupancy per Sq Mile',
    'title_es': 'Certificados de Ocupación Residencial por milla cuadrada',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
    'world_val': {
      y_2012: 6.8659644159280325,
      y_2013: 7.9873493131994080,
      y_2014: 7.8463368410874386,
      y_2015: 9.4814100296238454,
      y_2016: 10.8277433943119339,
      y_2017: 9.8406560895281483,
      y_2018: 11.7678265417250630,
      y_2019: 12.1069279627562275,
    }
  },
  'mCPMTS': {
    'metric': 'CPMTS',
    'category': 'Economy',
    'subcategory': 'Building Permits',
    'prefix': '$',
    'label': 'per sq mi',
    'raw_label': 'total dollars',
    'title': 'Commercial Building Permit Values Per Sq Mile',
    'title_es': 'Valores de los Permisos de Construcción Comercial por milla cuadrada',
    'decimals': 0,
    'type': 'weighted',
    'world_val': {
      y_2012: 953750.21,
      y_2013: 1557984.27,
      y_2014: 1129287.67,
      y_2015: 1064761.1,
      y_2016: 1619937.98,
      y_2017: 1842853.77,
      y_2018: 2155235.79,
      y_2019: 2369273.58,
    },
    'geographies': [
      'blockgroup',
      'tract',
    ],
  },
    'mRESIDENTIAL-DEMOLITION-PERMITS': {
    'metric': 'RESIDENTIAL-DEMOLITION-PERMITS',
    'category': 'Economy',
    'subcategory': 'Building Permits',
    'label': 'per sq mi',
    'raw_label': 'demolitions',
    'title': 'Home Demolitions Per Sq Mile',
    'title_es': 'Demoliciones de casas por milla cuadrada',
    'decimals': 2,
    'type': 'weighted',
    'world_val': {
      y_2012: 0.28873982384831823717,
      y_2013: 0.21151870816795405746,
      y_2014: 0.40289277746276963326,
      y_2015: 0.33910142103116444133,
      y_2016: 0.39617789783839013938,
      y_2017: 0.47004157370656457214,
      y_2018: 0.39282045802620039243,
      y_2019: 0.52711805051379027019,
    },
    'geographies': [
      'blockgroup',
      'tract',
    ],
  },
  'mDRALONE': {
    'metric': 'DRALONE',
    'accuracy': 'true',
    'category': 'Environment',
    'title': 'Single-Occupancy Commuters',
    'title_es': 'Viaje al trabajo sin acompañantes',
    'suffix': '%',
    'raw_label': 'commuters',
    'decimals': 1,
    'world_val': {
      y_2011: 75.2,
      y_2012: 75.2,
      y_2013: 75.2,
      y_2014: 75.6,
      y_2015: 74.9,
      y_2016: 75.7,
      y_2017: 76.8,
      y_2018: 77.0,
    },
    'type': 'weighted',
    'geographies': [
      'tract',
    ],
  },
  'mDIABETES_ASIAN': {
    'metric': 'DIABETES_ASIAN',
    'category': 'Health',
    'subcategory': 'Diabetes',
    'title': 'Diabetes (Asian Population)',
    'title_es': 'Diabetes (Población Asiática)',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 8.32, 'y_2017': 7.81},
    'geographies': [
      'tract',
    ],
  },
  'mDIABETES_BLACK': {
    'metric': 'DIABETES_BLACK',
    'category': 'Health',
    'subcategory': 'Diabetes',
    'title': 'Diabetes (Black or African American Population)',
    'title_es': 'Diabetes (Población Afroamericana o Negra)',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 18.99, 'y_2017': 18.36},
    'geographies': [
      'tract',
    ],
  },
  'mDIABETES_FEMALE': {
    'metric': 'DIABETES_FEMALE',
    'category': 'Health',
    'subcategory': 'Diabetes',
    'title': 'Diabetes (Female)',
    'title_es': 'Diabetes (Mujeres)',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 12.36, 'y_2017': 12.04},
    'geographies': [
      'tract',
    ],
  },
  'mDIABETES_HISPANIC': {
    'metric': 'DIABETES_HISPANIC',
    'category': 'Health',
    'subcategory': 'Diabetes',
    'title': 'Diabetes (Hispanic or Latino/a Population)',
    'title_es': 'Diabetes (Población Hispana o Latina)',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 13.95, 'y_2017': 13.25},
    'geographies': [
      'tract',
    ],
  },
  'mDIABETES_MALE': {
    'metric': 'DIABETES_MALE',
    'category': 'Health',
    'subcategory': 'Diabetes',
    'title': 'Diabetes (Male)',
    'title_es': 'Diabetes (Hombres)',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 14.67, 'y_2017': 14.15},
    'geographies': [
      'tract',
    ],
  },
  'mDIABETES_TOTAL': {
    'metric': 'DIABETES_TOTAL',
    'category': 'Health',
    'subcategory': 'Diabetes',
    'title': 'Diabetes (Adult Population)',
    'title_es': 'Diabetes (Población Adulta)',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 13.42, 'y_2017': 12.86},
    'geographies': [
      'tract',
    ],
  },
  'mDIABETES_WHITE': {
    'metric': 'DIABETES_WHITE',
    'category': 'Health',
    'subcategory': 'Diabetes',
    'title': 'Diabetes (White Population)',
    'title_es': 'Diabetes (Población Blanca)',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 9.69, 'y_2017': 9.23},
    'geographies': [
      'tract',
    ],
  },
  'mD_SQM': {
    'metric': 'D_SQM',
    'category': 'Safety',
    'title': 'Drug Crimes per Square Mile',
    'title_es': 'Delitos relacionados con drogas por milla cuadrada',
    'label': 'incidents per sq mi',
    'raw_label': 'incidents',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
    ],
  },
  //  "mHEARTATTACK_ASIAN": {
  //   "metric": "HEARTATTACK_ASIAN",
  //    "category": "Health",
  //    "title": "Heart Attack (Asian Population)",
  //   "suffix":"%",
  //    "raw_label": "adults",
  //    "decimals": 1,
  //    "type": "weighted",
  //    "world_val": {"y_2015": 0.70,"y_2017":0.63},
  //    "geographies": [
  //      "tract"
  //        ]
  //  },
  'mHEARTATTACK_BLACK': {
    'metric': 'HEARTATTACK_BLACK',
    'category': 'Health',
    'subcategory': 'Heart Attack',
    'title': 'Heart Attack (Black or African American Population)',
    'title_es': 'Ataque Cardíaco (Población Negra o Afroamericana)',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 2.38, 'y_2017': 2.16},
    'geographies': [
      'tract',
    ],
  },
  'mHEARTATTACK_FEMALE': {
    'metric': 'HEARTATTACK_FEMALE',
    'category': 'Health',
    'subcategory': 'Heart Attack',
    'title': 'Heart Attack (Female)',
    'title_es': 'Ataque Cardíaco (Mujeres)',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 1.47, 'y_2017': 1.31},
    'geographies': [
      'tract',
    ],
  },
  //  "mHEARTATTACK_HISPANIC": {
  //    "metric": "HEARTATTACK_HISPANIC",
  //   "category": "Health",
  //   "title": "Heart Attack (Hispanic or Latino/a Population)",
  //   "suffix":"%",
  //    "raw_label": "adults",
  //    "decimals": 1,
  //    "type": "weighted",
  //   "world_val": {"y_2015": 0.47,"y_2017":0.43},
  //    "geographies": [
  //      "tract"
  //        ]
  //  },
  'mHEARTATTACK_MALE': {
    'metric': 'HEARTATTACK_MALE',
    'category': 'Health',
    'subcategory': 'Heart Attack',
    'title': 'Heart Attack (Male)',
    'title_es': 'Ataque Cardíaco (Hombres)',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 3.02, 'y_2017': 2.70},
    'geographies': [
      'tract',
    ],
  },
  'mHEARTATTACK_TOTAL': {
    'metric': 'HEARTATTACK_TOTAL',
    'category': 'Health',
    'subcategory': 'Heart Attack',
    'title': 'Heart Attack (Adult Population)',
    'title_es': 'Ataque Cardíaco (Población Adulta)',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 2.08, 'y_2017': 1.86},
    'geographies': [
      'tract',
    ],
  },
  'mHEARTATTACK_WHITE': {
    'metric': 'HEARTATTACK_WHITE',
    'category': 'Health',
    'subcategory': 'Heart Attack',
    'title': 'Heart Attack (White Population)',
    'title_es': 'Ataque Cardíaco (Población Blanca)',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 2.33, 'y_2017': 2.08},
    'geographies': [
      'tract',
    ],
  },
  'mHMINC': {
    'metric': 'HMINC',
    'category': 'Economy',
    'subcategory': 'Income',
    'title': 'Median Homebuyer Income',
    'title_es': 'Mediana del Ingreso de los Compradores de Vivienda',
    'prefix': '$',
    'decimals': 0,
    'type': 'mean',
    'geographies': [
      'tract',
    ],
  },
  'mKWH': {
    'metric': 'KWH',
    'category': 'Environment',
    'title': 'Avg. Monthly Household Electricity Use',
    'title_es': 'Promedio Consumo mensual de electricidad por hogar',
    'suffix': ' kwh',
    'decimals': 0,
    'type': 'mean',
    'geographies': [
      'blockgroup',
    ],
  },
  'mLUDIV': {
    'metric': 'LUDIV',
    'category': 'Environment',
    'title': 'Land Use Diversity',
    'title_es': 'Diversidad en el Uso de la Tierra',
    'decimals': 1,
    'type': 'mean',
    'geographies': [
      'blockgroup',
    ],
  },
  'mMEANRPMT': {
    'metric': 'MEANRPMT',
    'category': 'Economy',
    'subcategory': 'Building Permits',
    'prefix': '$',
    'title': 'Average Residential Building Permit Value',
    'title_es': 'Promedio del Valor de los Permisos de Construcción Residencial',
    'decimals': 0,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
  },
  'mMEDAGE': {
    'metric': 'MEDAGE',
    'accuracy': 'true',
    'category': 'Demographics',
    'subcategory': 'Age',
    'label': 'years',
    'title': 'Median Age',
    'title_es': 'Mediana de Edad',
    'decimals': 1,
    'world_val': {
      y_2010: 33.2,
      y_2011: 33.3,
      y_2012: 33.4,
      y_2013: 33.7,
      y_2014: 34.1,
      y_2015: 34.4,
      y_2016: 34.6,
      y_2017: 35,
      y_2018: 35.2,
    },
    'type': 'mean',
    'geographies': [
      'tract',
      'blockgroup',
    ],
  },
  'mMEDGRENT': {
    'metric': 'MEDGRENT',
    'accuracy': true,
    'category': 'Housing',
    'title': 'Cost of Rent',
    'title_es': 'Costo del Arriendo',
    'prefix': '$',
    'decimals': 0,
    'world_val': {
      y_2010: 792,
      y_2011: 817,
      y_2012: 840,
      y_2013: 859,
      y_2014: 877,
      y_2015: 895,
      y_2016: 921,
      y_2017: 966,
      y_2018: 1014,
    },
    'type': 'weighted',
    'geographies': [
      'tract',
      'blockgroup',
    ],
  },
  // 'mMEDHV': {
  //   'metric': 'MEDHV',
  //   'category': 'Housing',
  //   'title': 'Median Home Value',
  //   'title_es': 'Mediana del Valor de Viviendas',
  //   'prefix': '$',
  //   'decimals': 0,
  //   'type': 'weighted',
  //   'geographies': [
  //     'tract',
  //   ],
  // },
  'mMEDINC': {
    'metric': 'MEDINC',
    'accuracy': true,
    'category': 'Economy',
    'subcategory': 'Income',
    'prefix': '$',
    'title': 'Median Household Income',
    'title_es': 'Mediana del Ingreso de los Hogares',
    'decimals': 0,
    'world_val': {
      y_2010: 49894,
      y_2011: 50078,
      y_2012: 50997,
      y_2013: 51853,
      y_2014: 52038,
      y_2015: 52503,
      y_2016: 54093,
      y_2017: 56393,
      y_2018: 58190,
    },
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
  },
  'mMEDINC-BLACK': {
    'metric': 'MEDINC-BLACK',
    'accuracy': 'true',
    'category': 'Economy',
    'subcategory': 'Income',
    'prefix': '$',
    'title': 'Median Household Income (Black Households)',
    'title_es': 'Mediana del Ingreso de los Hogares Negras o Afroamericanas',
    'decimals': 0,
    'world_val': {
      y_2010: 36631,
      y_2011: 37057,
      y_2012: 37199,
      y_2013: 37757,
      y_2014: 38295,
      y_2015: 39332,
      y_2016: 40855,
      y_2017: 41804,
      y_2018: 42417,
      y_2019: 44099,
    },
    'type': 'weighted',
    'geographies': [
      'tract',
    ],
  },
  'mMEDINC-WHITE': {
    'metric': 'MEDINC-WHITE',
    'accuracy': 'true',
    'category': 'Economy',
    'subcategory': 'Income',
    'prefix': '$',
    'title': 'Median Household Income (White Households)',
    'title_es': 'Mediana del Ingreso de los Hogares Blancas',
    'decimals': 0,
    'world_val': {
      y_2010: 65561,
      y_2011: 65726,
      y_2012: 67146,
      y_2013: 67994,
      y_2014: 68790,
      y_2015: 68413,
      y_2016: 70494,
      y_2017: 73745,
      y_2018: 76962,
      y_2019: 80409,
    },
    'type': 'weighted',
    'geographies': [
      'tract',
    ],
  },
  'mMEDINC-HISPANIC': {
    'metric': 'MEDINC-HISPANIC',
    'accuracy': 'true',
    'category': 'Economy',
    'subcategory': 'Income',
    'prefix': '$',
    'title': 'Median Household Income (Hispanic or Latino/a Households)',
    'title_es': 'Mediana del Ingreso de los Hogares Hispanas o Latinas',
    'decimals': 0,
    'world_val': {
      y_2010: 38750,
      y_2011: 39079,
      y_2012: 39215,
      y_2013: 40654,
      y_2014: 40623,
      y_2015: 39025,
      y_2016: 41512,
      y_2017: 42638,
      y_2018: 44004,
      y_2019: 47587,
    },
    'type': 'weighted',
    'geographies': [
      'tract',
    ],
  },
  'mPCI': {
    'metric': 'PCI',
    'accuracy': true,
    'category': 'Economy',
    'subcategory': 'Income',
    'prefix': '$',
    'title': 'Per Capita Income',
    'title_es': 'Ingreso Per Cápita',
    'decimals': 0,
    'world_val': {
      y_2010: 27334,
      y_2011: 27915,
      y_2012: 28051,
      y_2013: 28155,
      y_2014: 28555,
      y_2015: 28930,
      y_2016: 29829,
      y_2017: 31177,
      y_2018: 32621,
    },
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
  },
  'mPCTC30': {
    'metric': 'PCTC30',
    'accuracy': 'true',
    'category': 'Environment',
    'title': 'Long Commute Times',
    'title_es': 'Viaje al trabajo extenso',
    'suffix': '%',
    'raw_label': 'commuters',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'tract',
    ],
  },
  'mPCTIMP': {
    'metric': 'PCTIMP',
    'category': 'Environment',
    'title': 'Impervious Area',
    'title_es': 'Áreas Impermeables',
    'suffix': '%',
    'raw_label': 'square miles',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
    'world_val': {
      y_2001: 6.994631263962856,
      y_2006: 7.737930551747872,
      y_2011: 8.350512433138704,
      y_2016: 8.738632850551514,
    },
  },
  'mPCTRENT': {
    'metric': 'PCTRENT',
    'accuracy': true,
    'category': 'Housing',
    'title': 'Renter-Occupied Housing',
    'title_es': 'Vivienda Ocupada por Inquilinos',
    'suffix': '%',
    'raw_label': 'renter households',
    'decimals': 1,
    'world_val': {
      y_2011: 44.6,
      y_2012: 45.0,
      y_2013: 45.0,
      y_2014: 45.6,
      y_2015: 46.3,
      y_2016: 46.9,
      y_2017: 46.5,
      y_2018: 46.2,
    },
    'type': 'weighted',
    'geographies': [
      'blockgroup',
    ],
  },
  'mPCTSSI': {
    'metric': 'PCTSSI',
    'accuracy': 'true',
    'category': 'Economy',
    'subcategory': 'Income',
    'suffix': '%',
    'raw_label': 'people receiving SSI',
    'title': 'Supplemental Security Income',
    'title_es': 'Seguridad de Ingreso Suplementario',
    'decimals': 1,
    'world_val': {
      y_2010: 2.8,
      y_2011: 3.3,
      y_2012: 3.5,
      y_2013: 3.7,
      y_2014: 3.9,
      y_2015: 4.0,
      y_2016: 4.0,
      y_2017: 4.1,
      y_2018: 4.0,
    },
    'type': 'weighted',
    'geographies': [
      'tract',
    ],
  },
  'mPCTTREE': {
    'metric': 'PCTTREE',
    'category': 'Environment',
    'title': 'Tree Coverage',
    'title_es': 'Cobertura arbórea',
    'suffix': '%',
    'raw_label': 'square miles',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
    'world_val': {
      'y_2011': 59.12818457776564,
      'y_2016': 57.4262731894659,
    },
  },
  // Note: Health Indicators App currently uses the raw POP metric, so those metric files should be
  // preserved for the time being.
  'mPOP': {
    'metric': 'POP',
    'category': 'Demographics',
    'label': 'people',
    'title': 'Population',
    'title_es': 'Población',
    'decimals': 0,
    'type': 'sum',
    'geographies': [
      'blockgroup',
    ],
    'exclude_from_map': true,
  },
  'mPOPDENS': {
    'metric': 'POPDENS',
    'category': 'Demographics',
    'label': 'people per sq mi',
    'title': 'Population Density',
    'title_es': 'Densidad de Población',
    'raw_label': 'people',
    'decimals': 0,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
    ],
  },
  'mPROXBANK': {
    'metric': 'PROXBANK',
    'category': 'Infrastructure and Amenities',
    'suffix': '%',
    'raw_label': 'households',
    'title': 'Homes Near Banks or Credit Unions',
    'title_es': 'Viviendas cerca de bancos y uniones de crédito',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
    ],
  },
  'mPROXBUS': {
    'metric': 'PROXBUS',
    'category': 'Infrastructure and Amenities',
    'suffix': '%',
    'raw_label': 'households',
    'title': 'Homes Near Bus Stops',
    'title_es': 'Viviendas cerca de paradas de autobús',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
    ],
  },
  'mPROXCF': {
    'metric': 'PROXCF',
    'category': 'Infrastructure and Amenities',
    'suffix': '%',
    'raw_label': 'households',
    'title': 'Homes Near Fast Food & Convenience Stores',
    'title_es': 'Viviendas cerca de locales de comida rápida y tiendas de conveniencia',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
    ],
  },
  'mPROXGR': {
    'metric': 'PROXGR',
    'category': 'Infrastructure and Amenities',
    'suffix': '%',
    'raw_label': 'households',
    'title': 'Homes Near Grocery Stores',
    'title_es': 'Viviendas cerca de supermercados',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
    ],
  },
  'mPROXPH': {
    'metric': 'PROXPH',
    'category': 'Health',
    'suffix': '%',
    'raw_label': 'households',
    'title': 'Homes Near Pharmacies',
    'title_es': 'Viviendas cerca de farmacias',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
    ],
  },
  'mPRUNSD': {
    'metric': 'PRUNSD',
    'category': 'Housing',
    'title': 'Deteriorated Properties',
    'title_es': 'Propiedades Deterioradas',
    'suffix': '%',
    'raw_label': 'dwelling units in poor or unsound state of repair',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
    ],
  },
  'mPT65UP': {
    'metric': 'PT65UP',
    'category': 'Demographics',
    'subcategory': 'Age',
    'accuracy': true,
    'title': 'Retirement-Age Population',
    'title_es': 'Población en Edad de Jubilación',
    'suffix': '%',
    'raw_label': 'people',
    'decimals': 1,
    'world_val': {
      y_2010: 8.2,
      y_2015: 9.2,
      y_2016: 9.6,
      y_2017: 11.6,
      y_2018: 12.1,
    },
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
  },
  'mPTASNL': {
    'metric': 'PTASNL',
    'accuracy': true,
    'category': 'Demographics',
    'subcategory': 'Race/Ethnicity',
    'suffix': '%',
    'raw_label': 'people',
    'title': 'Asian Population',
    'title_es': 'Población Asiática',
    'decimals': 1,
    'world_val': {
      y_2010: 4.6,
      y_2015: 4.6,
      y_2016: 4.7,
      y_2017: 4.7,
      y_2018: 4.9,
    },
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
  },
  'mPTAIAN': {
    'metric': 'PTAIAN',
    'accuracy': true,
    'category': 'Demographics',
    'subcategory': 'Race/Ethnicity',
    'suffix': '%',
    'raw_label': 'people',
    'title': 'Indigenous Population',
    'title_es': 'Población indígena',
    'decimals': 2,
    'world_val': {
      y_2010: 1.14,
      y_2011: 1.32,
      y_2016: 0.95,
    },
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
  },
  'mPTBLKNL': {
    'metric': 'PTBLKNL',
    'accuracy': 'true',
    'category': 'Demographics',
    'subcategory': 'Race/Ethnicity',
    'suffix': '%',
    'raw_label': 'people',
    'title': 'Black or African American Population',
    'title_es': 'Población Negra o afroamericana',
    'decimals': 1,
    'world_val': {
      y_2010: 37.5,
      y_2015: 37.1,
      y_2016: 37.2,
      y_2017: 36.9,
      y_2018: 36.5,
    },
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
  },
  'mPTGNRL': {
    'metric': 'PTGNRL',
    'category': 'Civic Engagement',
    'title': 'General Election Participation',
    'title_es': 'Participación en Elecciones Generales',
    'suffix': '%',
    'raw_label': 'voters',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
    ],
  },
  'mPTLAT': {
    'metric': 'PTLAT',
    'accuracy': 'true',
    'category': 'Demographics',
    'subcategory': 'Race/Ethnicity',
    'suffix': '%',
    'raw_label': 'people',
    'title': 'Hispanic/Latino Population',
    'title_es': 'Hispano/Latino',
    'decimals': 1,
    'world_val': {
      y_2010: 13.5,
      y_2015: 13.4,
      y_2016: 13.3,
      y_2017: 13.5,
      y_2018: 13.4,
    },
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
  },
  'mPTPRIM': {
    'metric': 'PTPRIM',
    'category': 'Civic Engagement',
    'title': 'Primary Election Participation',
    'title_es': 'Participación en Elecciones Primarias',
    'suffix': '%',
    'raw_label': 'voters',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
    ],
  },
  'mPTUND18': {
    'metric': 'PTUND18',
    'category': 'Demographics',
    'subcategory': 'Age',
    'title': 'Youth Population',
    'title_es': 'Población menor de 18 años',
    'suffix': '%',
    'raw_label': 'young people',
    'decimals': 1,
    'world_val': {
      y_2010: 24.4,
      y_2015: 23.5,
      y_2016: 23.4,
      y_2017: 21.7,
      y_2018: 21.4,
    },
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
  },
  'mPTWHNL': {
    'metric': 'PTWHNL',
    'accuracy': 'true',
    'category': 'Demographics',
    'subcategory': 'Race/Ethnicity',
    'suffix': '%',
    'raw_label': 'people',
    'title': 'White Population',
    'title_es': 'Población Blanca',
    'decimals': 1,
    'world_val': {
      y_2010: 42.1,
      y_2015: 42.1,
      y_2016: 42.0,
      y_2017: 42.1,
      y_2018: 42.2,
    },
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
  },
  'mPTPOC': {
    'metric': 'PTPOC',
    'accuracy': 'true',
    'category': 'Demographics',
    'subcategory': 'Race/Ethnicity',
    'suffix': '%',
    'raw_label': 'people',
    'title': 'People of Color',
    'title_es': 'Personas de color',
    'decimals': 1,
    'world_val': {
      y_2010: 57.9,
      y_2016: 57.8,
    },
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
  },
  'mP_SQM': {
    'metric': 'P_SQM',
    'category': 'Safety',
    'title': 'Property Crimes per Square Mile',
    'title_es': 'Delitos a la propiedad por milla cuadrada',
    'label': 'crimes per sq mi',
    'raw_label': 'crimes',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
    ],
  },
  'mRAVGYR': {
    'metric': 'RAVGYR',
    'category': 'Housing',
    'title': 'Average Year of Residential Construction',
    'title_es': 'Año Promedio de Construcción Residencial',
    'decimals': 0,
    'commas': false,
    'type': 'mean',
    'geographies': [
      'blockgroup',
    ],
  },
  'mRCODE': {
    'metric': 'RCODE',
    'category': 'Housing',
    'title': 'Housing Code Violations',
    'title_es': 'Violaciones al Código de Estándares de Vivienda',
    'label': 'violations per sq mi',
    'raw_label': 'violations',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
    'world_val': {
      y_2012: 18.7168926242343567,
      y_2013: 20.6949578381623652,
      y_2014: 13.1695186242851415,
      y_2015: 10.5408897399985879,
      y_2016: 11.6046492550443170,
      y_2017: 11.1738706084555506,
      y_2018: 13.1431444214327681,
      y_2019: 12.1409247130425771,
      y_2020: 11.2529932170126710,
    },
  },
  'mREDIV': {
    'metric': 'REDIV',
    'category': 'Demographics',
    'subcategory': 'Race/Ethnicity',
    'title': 'Race/Ethnic Diversity',
    'title_es': 'Diversidad Racial/Étnica',
    'decimals': 2,
    'type': 'mean',
    'geographies': [
      'blockgroup',
    ],
  },
  'mRESIDENTIAL-SALE-PRICE': {
    'metric': 'RESIDENTIAL-SALE-PRICE',
    'category': 'Housing',
    'title': 'Sale Price',
    'title_es': 'Precio de Venta',
    'prefix': '$',
    'decimals': 0,
    'type': 'mean',
    'label': 'median sale price',
    'world_val': {
      y_1998: 123500,
      y_1999: 129000,
      y_2000: 135000,
      y_2001: 143500,
      y_2002: 150000,
      y_2003: 155000,
      y_2004: 163000,
      y_2005: 170000,
      y_2006: 175000,
      y_2007: 180000,
      y_2008: 185000,
      y_2009: 190000,
      y_2010: 190000,
      y_2011: 193000,
      y_2012: 198000,
      y_2013: 207000,
      y_2014: 216000,
      y_2015: 229000,
      y_2016: 245000,
      y_2017: 262000,
      y_2018: 273000,
      y_2019: 283000,
      y_2020: 290500,
    },
    'geographies': [
      'blockgroup',
      'tract',
    ],
  },
  'mREVAL': {
    'metric': 'REVAL',
    'category': 'Housing',
    'title': 'Tax Value Change',
    'title_es': 'Cambio de Valor Impositivo',
    'suffix': '%',
    'decimals': 1,
    'type': 'mean',
    'geographies': [
      'blockgroup',
    ],
  },
  'mRPMTS': {
    'metric': 'RPMTS',
    'category': 'Economy',
    'subcategory': 'Building Permits',
    'prefix': '$',
    'title': 'Residential Building Permit Value Per Sq Mile',
    'title_es': 'Promedio del Valor de los Permisos de Construcción Residencial por milla cuadrada',
    'label': 'per sq mi',
    'raw_label': 'total dollars',
    'decimals': 0,
    'world_val': {
      y_2012: 1358105.54,
      y_2013: 1569905.53,
      y_2014: 1252480.49,
      y_2015: 1558094.64,
      y_2016: 2087390.7,
      y_2017: 2398384.62,
      y_2018: 2376536.5,
      y_2019: 2514926.6,
    },
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
  },
  'mOUT-OF-STATE-VALUE': {
    'metric': 'OUT-OF-STATE-VALUE',
    'category': 'Housing',
    'subcategory': 'Ownership',
    'title': 'Out of state ownership (all properties)',
    'suffix': '%',
    'title_es': 'Propietarios con residencia fuera del estado\n',
    'raw_label': 'total dollars',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
    'world_val': {
      y_2001: 14.7399036451658,
      y_2002: 15.6154866393285,
      y_2003: 15.7477585877851,
      y_2004: 14.847240661382,
      y_2005: 15.6290434702396,
      y_2007: 16.1938551263775,
      y_2008: 18.6909560143541,
      y_2009: 19.4955448629218,
      y_2010: 18.3611973234924,
      y_2011: 18.144354990264,
      y_2012: 18.1227219686585,
      y_2013: 18.6536648079158,
      y_2014: 18.9214249467994,
      y_2015: 20.0504060270684,
      y_2016: 22.2382344504687,
      y_2017: 21.708354213035,
      y_2018: 23.1253442868151,
      y_2019: 22.7549922639719,
      y_2020: 23.4461127193014,
    },
  },
  'mOUT-OF-STATE-RES-VALUE': {
    'metric': 'OUT-OF-STATE-RES-VALUE',
    'category': 'Housing',
    'subcategory': 'Ownership',
    'title': 'Out of state ownership (residential properties)',
    'suffix': '%',
    'title_es': 'Propietarios con residencia fuera del estado',
    'raw_label': 'total dollars',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
    'world_val': {
      y_2001: 9.56126999147088,
      y_2002: 9.97775172465329,
      y_2003: 9.96512522912126,
      y_2004: 9.84489613167733,
      y_2005: 9.92434698168726,
      y_2007: 10.6373182507551,
      y_2008: 10.6300195478971,
      y_2009: 10.4597792611371,
      y_2010: 10.3164374942415,
      y_2011: 10.8117045855789,
      y_2012: 11.3893327955147,
      y_2013: 11.9527965660164,
      y_2014: 12.5069220951569,
      y_2015: 13.2603256834365,
      y_2016: 13.8323812930625,
      y_2017: 13.6997652455985,
      y_2018: 14.3793338826355,
      y_2019: 15.4139301597914,
      y_2020: 16.3489370173807,
    },
  },
  //  "mSTROKE_ASIAN": {
  //   "metric": "STROKE_ASIAN",
  //    "category": "Health",
  //    "title": "Stroke (Asian Population)",
  //   "suffix":"%",
  //    "raw_label": "adults",
  //    "decimals": 1,
  //    "type": "weighted",
  //    "world_val": {"y_2015": 1.22,"y_2017":1.21},
  //    "geographies": [
  //      "tract"
  //        ]
  //  },
  'mSTROKE_BLACK': {
    'metric': 'STROKE_BLACK',
    'category': 'Health',
    'subcategory': 'Stroke',
    'title': 'Stroke (Black or African American Population)',
    'title_es': 'Accidente Cerebrovascular (Población Negra o Afroamericana)',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {
      'y_2015': 3.79,
      'y_2017': 3.34,
    },
    'geographies': [
      'tract',
    ],
  },
  'mSTROKE_FEMALE': {
    'metric': 'STROKE_FEMALE',
    'category': 'Health',
    'subcategory': 'Stroke',
    'title': 'Stroke (Female)',
    'title_es': 'Accidente Cerebrovascular (Mujeres)',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 2.89, 'y_2017': 2.45},
    'geographies': [
      'tract',
    ],
  },
  //  "mSTROKE_HISPANIC": {
  //    "metric": "STROKE_HISPANIC",
  //    "category": "Health",
  //    "title": "Stroke (Hispanic or Latino/a Population)",
  //   "suffix":"%",
  //    "raw_label": "adults",
  //    "decimals": 1,
  //    "type": "weighted",
  //   "world_val": {"y_2015": 0.82,"y_2017":0.65},
  //    "geographies": [
  //      "tract"
  //        ]
  //  },
  'mSTROKE_MALE': {
    'metric': 'STROKE_MALE',
    'category': 'Health',
    'subcategory': 'Stroke',
    'title': 'Stroke (Male)',
    'title_es': 'Accidente Cerebrovascular (Hombres)',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 3.78, 'y_2017': 3.23},
    'geographies': [
      'tract',
    ],
  },
  'mSTROKE_TOTAL': {
    'metric': 'STROKE_TOTAL',
    'category': 'Health',
    'subcategory': 'Stroke',
    'title': 'Stroke (Adult Population)',
    'title_es': 'Accidente Cerebrovascular (Población Adulta)',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 3.24, 'y_2017': 2.76},
    'geographies': [
      'tract',
    ],
  },
  'mSTROKE_WHITE': {
    'metric': 'STROKE_WHITE',
    'category': 'Health',
    'subcategory': 'Stroke',
    'title': 'Stroke (White Population)',
    'title_es': 'Accidente Cerebrovascular (Población Blanca)',
    'suffix': '%',
    'raw_label': 'adults',
    'decimals': 1,
    'type': 'weighted',
    'world_val': {'y_2015': 3.52, 'y_2017': 2.95},
    'geographies': [
      'tract',
    ],
  },
  'mSUMEJECT': {
    'metric': 'SUMEJECT',
    'category': 'Housing',
    'title': 'Evictions (Summary Ejectments)',
    'title_es': 'Desalojos (Desalojos Sumarios)',
    'label': 'evictions per sq mi',
    'raw_label': 'evictions',
    'decimals': 0,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
  },
  'mSWTORD': {
    'metric': 'SWTORD',
    'category': 'Safety',
    'suffix': '%',
    'title': 'Sidewalk Coverage',
    'title_es': 'Aceras a carreteras',
    'label': 'ratio of sidewalks to roadways',
    'decimals': 0,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
    ],
  },
  'mUNFOWN': {
    'metric': 'UNFOWN',
    'accuracy': 'true',
    'category': 'Housing',
    'title': 'Cost-Burdened Mortgage Holders',
    'title_es': 'Hogares con demasiados costos',
    'suffix': '%',
    'raw_label': 'households',
    'decimals': 1,
    'world_val': {
      y_2011: 31.2,
      y_2012: 29.5,
      y_2013: 28.5,
      y_2014: 28.3,
      y_2015: 26.7,
      y_2016: 24.5,
      y_2017: 22.7,
      y_2018: 22.8,
    },
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
  },
  'mUNFRENT': {
    'metric': 'UNFRENT',
    'accuracy': 'true',
    'category': 'Housing',
    'title': 'Cost-Burdened Renters',
    'title_es': 'Arrendatarios con demasiados costos',
    'suffix': '%',
    'raw_label': 'renter households',
    'decimals': 1,
    'world_val': {
      y_2011: 53.9,
      y_2012: 53.7,
      y_2013: 53.5,
      y_2014: 53.8,
      y_2015: 52.8,
      y_2016: 51.7,
      y_2017: 51.2,
      y_2018: 51.6,
    },
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
  },
  'mVCODE': {
    'metric': 'VCODE',
    'category': 'Environment',
    'title': 'Automotive Code Violations',
    'title_es': 'Violaciones al Código de Automóviles',
    'label': 'violations per sq mi',
    'raw_label': 'violations',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
    'world_val': {
      y_2012: 4.3429520696908277,
      y_2013: 2.9714935213674084,
      y_2014: 2.7517084975976297,
      y_2015: 2.6374202852373448,
      y_2016: 3.7803024088401942,
      y_2017: 4.5099886877558595,
      y_2018: 5.5034169951952594,
      y_2019: 6.1803548684061779,
      y_2020: 3.2176527479895606,
    },
  },
  'mV_SQM': {
    'metric': 'V_SQM',
    'category': 'Safety',
    'title': 'Violent Crimes per Square Mile',
    'title_es': 'Delitos violentos por milla cuadrada',
    'label': 'incidents per sq mi',
    'raw_label': 'incidents',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
    ],
  },
  'mWCODE': {
    'metric': 'WCODE',
    'category': 'Environment',
    'title': 'Unmaintained Property Violations per Sq Mile',
    'title_es': 'Violaciones por Propiedades No Mantenidas por milla cuadrada',
    'label': 'violations per sq mi',
    'raw_label': 'violations',
    'decimals': 1,
    'type': 'weighted',
    'geographies': [
      'blockgroup',
      'tract',
    ],
    'world_val': {
      y_2012: 17.7498385196473303,
      y_2013: 21.1872762914066696,
      y_2014: 21.2576074990129988,
      y_2015: 22.2246616036000252,
      y_2016: 28.2555626558427536,
      y_2017: 23.2444641138917985,
      y_2018: 25.8291359934243964,
      y_2019: 21.5916807351430625,
      y_2020: 18.1366601614821408,
    },
  },
  'mBUSWK': {
    'metric': 'BUSWK',
    'accuracy': 'true',
    'category': 'Infrastructure and Amenities',
    'suffix': '%',
    'raw_label': 'people',
    'title': 'Taking Public Transportation to Work',
    'title_es': 'Viaje al Trabajo en Transporte Público',
    'decimals': 1,
    'world_val': {
      y_2011: 3.3,
      y_2012: 3.3,
      y_2013: 3.6,
      y_2014: 3.8,
      y_2015: 3.9,
      y_2016: 4.1,
      y_2017: 3.7,
      y_2018: 3.4,
    },
    'type': 'weighted',
    'geographies': [
      'tract',
    ],
  },
  'mWKHOME': {
    'metric': 'WKHOME',
    'accuracy': 'true',
    'category': 'Infrastructure and Amenities',
    'suffix': '%',
    'raw_label': 'people',
    'title': 'Working from Home',
    'title_es': 'Trabajo desde la Vivienda',
    'decimals': 1,
    'world_val': {
      y_2011: 4.2,
      y_2012: 4.3,
      y_2013: 4.4,
      y_2014: 4.4,
      y_2015: 4.8,
      y_2016: 4.8,
      y_2017: 5.0,
      y_2018: 5.2,
    },
    'type': 'weighted',
    'geographies': [
      'tract',
    ],
  },
  'mWLKWK': {
    'metric': 'WLKWK',
    'accuracy': 'true',
    'category': 'Infrastructure and Amenities',
    'suffix': '%',
    'raw_label': 'people',
    'title': 'Walking to Work',
    'title_es': 'Ir al Trabajo Caminando',
    'decimals': 1,
    'world_val': {
      y_2011: 2.5,
      y_2012: 2.6,
      y_2013: 2.9,
      y_2014: 2.8,
      y_2015: 2.6,
      y_2016: 2.5,
      y_2017: 2.3,
      y_2018: 2.3,
    },
    'type': 'weighted',
    'geographies': [
      'tract',
    ],
  },
};
